from flask import Flask, request, jsonify
from flask_limiter import Limiter
from flask_limiter.util import get_remote_address
from dotenv import load_dotenv
import os
import uuid
import json
from datetime import datetime
from groq import Groq
import re


load_dotenv()

client = Groq(api_key=os.getenv("GROQ_API_KEY"))


app = Flask(__name__)

limiter = Limiter(
    get_remote_address,
    app=app,
    default_limits=[],
    storage_uri="memory://",
)

def groq_signal(text):
    prompt = f"""You are an AI content detector. Analyze the following text and determine 
the probability that it was AI-generated (vs written by a human).

Respond with ONLY a JSON object in this exact format:
{{"ai_probability": 0.0, "reasoning": "brief explanation"}}

The ai_probability should be a float between 0 and 1, where:
- 1.0 = certainly AI-generated
- 0.0 = certainly human-written

Text to analyze:
{text}"""

    response = client.chat.completions.create(
        model="llama-3.3-70b-versatile",
        messages=[{"role": "user", "content": prompt}],
        temperature=0.1,
    )
    
    result = json.loads(response.choices[0].message.content)
    return result["ai_probability"]

LOG_FILE = "audit_log.json"

def write_log(entry):
    logs = []
    if os.path.exists(LOG_FILE):
        with open(LOG_FILE, "r") as f:
            logs = json.load(f)
    logs.append(entry)
    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

def read_log():
    if not os.path.exists(LOG_FILE):
        return []
    with open(LOG_FILE, "r") as f:
        return json.load(f)

def stylometric_signal(text):
    sentences = [s.strip() for s in re.split(r'[.!?]+', text) if s.strip()]
    words = text.lower().split()

    if len(sentences) < 2 or len(words) < 10:
        return 0.5  # not enough data, return neutral

    # sentence length variance (low variance = more AI-like)
    lengths = [len(s.split()) for s in sentences]
    mean_len = sum(lengths) / len(lengths)
    variance = sum((l - mean_len) ** 2 for l in lengths) / len(lengths)
    variance_score = 1 / (1 + variance * 0.1)  # high variance = lower score (more human)

    # type-token ratio (low TTR = more AI-like)
    ttr = len(set(words)) / len(words)
    ttr_score = 1 - ttr  # low TTR = high AI score

    # punctuation density (high density = more AI-like)
    punct_count = sum(1 for c in text if c in ',;:()—–')
    punct_density = punct_count / len(words)
    punct_score = min(punct_density * 5, 1.0)

    return round((variance_score + ttr_score + punct_score) / 3, 3)

def get_label(confidence):
    if confidence >= 0.70:
        return ("Our system has determined with high confidence that this content "
                "was likely AI-generated. This assessment is based on writing style "
                "and structural analysis. If you believe this is incorrect, you may "
                "submit an appeal.")
    elif confidence >= 0.40:
        return ("Our system could not confidently determine whether this content "
                "was written by a human or generated by AI. It has been marked for "
                "review. If you are the creator, you may submit an appeal to provide "
                "additional context.")
    else:
        return ("Our system has determined with high confidence that this content "
                "was likely written by a human. No further action is required.")



@app.route("/submit", methods=["POST"])
@limiter.limit("10 per minute;100 per day")
def submit():
    data = request.get_json()
    text = data.get("text")
    creator_id = data.get("creator_id")
    content_id = str(uuid.uuid4())

    llm_score = groq_signal(text)
    stylo_score = stylometric_signal(text)

    # weighted average: 60% LLM, 40% stylometric
    confidence = round(0.6 * llm_score + 0.4 * stylo_score, 3)

    if confidence >= 0.70:
        attribution = "likely_ai"
    elif confidence >= 0.40:
        attribution = "uncertain"
    else:
        attribution = "likely_human"

    label = get_label(confidence)

    entry = {
        "content_id": content_id,
        "creator_id": creator_id,
        "timestamp": datetime.utcnow().isoformat() + "Z",
        "attribution": attribution,
        "confidence": confidence,
        "llm_score": llm_score,
        "stylo_score": stylo_score,
        "status": "classified"
    }
    write_log(entry)
    
    return jsonify({
        "content_id": content_id,
        "attribution": attribution,
        "confidence": confidence,
        "label": label
    })

@app.route("/log", methods=["GET"])
def get_log():
    return jsonify({"entries": read_log()})

@app.route("/appeal", methods=["POST"])
def appeal():
    data = request.get_json()
    content_id = data.get("content_id")
    reasoning = data.get("creator_reasoning")

    logs = read_log()
    entry = next((e for e in logs if e["content_id"] == content_id), None)

    if not entry:
        return jsonify({"error": "content_id not found"}), 404

    entry["status"] = "under_review"
    entry["appeal_reasoning"] = reasoning
    entry["appeal_timestamp"] = datetime.utcnow().isoformat() + "Z"

    with open(LOG_FILE, "w") as f:
        json.dump(logs, f, indent=2)

    return jsonify({
        "message": "Appeal received. Your content has been marked for human review.",
        "content_id": content_id,
        "status": "under_review"
    })

if __name__ == "__main__":
    app.run(debug=True)